PersonalBlogApp/PersonalBlogApp/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PersonalBlogApp.Models;
using PersonalBlogApp.Requests;
using PersonalBlogApp.Services;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis.CodeFixes;
using System.Security.Claims;

namespace PersonalBlogApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Register() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([FromForm] UserRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _authService.Register(request);
            if (result.Status != 201)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
                return View(request);
            }
            else
            {
                TempData["Success"] = result.Result.ToString();
            }

            return RedirectToAction("Login");
        }

        [HttpGet]
        public  IActionResult Login() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([FromForm] LoginRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _authService.Login(request);
            if (result.Status != 200)
            { 
               ModelState.AddModelError(string.Empty, result.Result.ToString());              
               return View(request);
            }
            return Redirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            var result = await _authService.Logout();
            return Redirect("/");
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(request);
                }

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                request.userId = userId;

                var result = await _authService.ChangePassword(request);
                TempData["Success"] = result;
                return View();
            } catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

PersonalBlogApp/PersonalBlogApp/Controllers/BlogsController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PersonalBlogApp.Models;
using PersonalBlogApp.Requests;
using PersonalBlogApp.Responses;
using PersonalBlogApp.Services;

namespace PersonalBlogApp.Controllers
{
    [Authorize]
    public class BlogsController : Controller
    {
        private readonly IBlogService _blogService;

        public BlogsController(IBlogService blogService) => _blogService = blogService;

        // get all blogs for user
        public async Task<IActionResult> Index()
        {
            var result = await _blogService.GetAllAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Manage() => View();

        [HttpGet]
        public async Task<IActionResult> GetBlogsPagination([FromQuery] PaginationRequest request)
        {
            request.Start = (request.Start / request.Length) + 1;
     
            var userId = HttpContext.Items["UserId"]?.ToString();
            var isAdmin = HttpContext.Items["IsAdmin"] as bool? ?? false;

            request.CurrentUserId = userId;
            request.IsAdmin = isAdmin;

            var result = await _blogService.GetBlogsPagination(request);

            return Json(result);
        }

        // go to add blog view
        [HttpGet]
        public IActionResult Create() => View();
        

        // add blog
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] BlogRequest request)
        {
            if(!ModelState.IsValid)
            {
                return View(); 
            }

            var result = await _blogService.CreateAsync(request);
            return RedirectToAction("Details", new { id = result.Id });
        }

        // get detail
        [HttpGet("Blogs/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _blogService.GetByIdAsync(id);
            if (result == null) {
                TempData["Error"] = "This blog is not exist";
                return RedirectToAction("GetAll");
            }
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _blogService.GetByIdAsync(id);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] BlogRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Edit", new { id = request.Id });
                }

                var result = await _blogService.UpdateAsync(request);
                TempData["Success"] = "Edit blog successfully";
                return RedirectToAction("Details", new { id = request.Id });
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Edit", new { id = request.Id });
            }
        }

        [HttpDelete("Blogs/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _blogService.DeleteAsync(id);
            return Json(result);
        }
    }
}

PersonalBlogApp/PersonalBlogApp/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@using System.Security.Claims

@{
	var currentUser = User.Identity.Name;
	var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - PersonalBlogApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/PersonalBlogApp.styles.css" asp-append-version="true" />
	<!-- Toastr CSS -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

	<!-- Toastr JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	@Html.AntiForgeryToken()
	<meta name="csrf-token" content="@Antiforgery.GetAndStoreTokens(ViewContext.HttpContext).RequestToken" /> @* ValidateAntiForgeryToken *@
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Blogs" asp-action="Index">BlogApp</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<div>
						<ul class="navbar-nav flex-grow-1">
							@if (User.IsInRole("Admin"))
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-action="Index" asp-controller="Users">Users</a>
								</li>
							}
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Blogs" asp-action="Manage">Blogs</a>
							</li>
							@if (User.Identity.IsAuthenticated)
							{
								<li class="nav-item">
									<h5 class="nav-link text-danger mb-0">@currentUser</h5>
								</li>
							}
						</ul>
					</div>
					<div>
						<div class="dropdown">
							<button class="btn btn-link dropdown-toggle" type="button" id="personal-information" data-bs-toggle="dropdown" aria-expanded="false">
								Settings
							</button>
							<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="personal-information">
								@if (User.Identity.IsAuthenticated)
								{
									<li class="nav-item">
										<a class="text-decoration-none" asp-action="Details" asp-controller="Users" asp-route-id="@currentUserId"><h5 class="nav-link text-danger mb-0">@currentUser</h5></a>
									</li>
								}
								<li class="nav-item">
									<a class="nav-link text-dark" asp-controller="Auth" asp-action="ChangePassword">Change Password</a>
								</li>
								@if (User.Identity.IsAuthenticated)
								{
									<li class="nav-item">
										<form asp-action="Logout" asp-controller="Auth" method="post" class="d-inline">
											<button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
										</form>
									</li>
								}
								else
								{
									<li class="nav-item">
										<a style="cursor: pointer" class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
									</li>
								}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - PersonalBlogApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	@* ------------Custom------------- *@
	<script src="~/js/auth.js" asp-append-version="true"></script>
	@* ------------Custom------------- *@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<!-- jQuery (required for toastr) -->
	<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
	<!-- Toastr JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>